name: Verify Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Run
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: ./.github/actions/node

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restoring Node.js
        uses: ./.github/actions/node
      - name: Lint Code
        run: pnpm check:lint
        env:
          CI: true

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restoring Node.js
        uses: ./.github/actions/node
      - name: Test
        run: pnpm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restoring Node.js
        uses: ./.github/actions/node
      - name: Build
        run: pnpm build
        env:
          CI: true
